K



OK



d
AT+CVHU=0


OK


e
ATI


SIM800 R13.08

f
AT+GMM




OK



SIMCOM
g
AT+CPMS="SM","SM",SM"
_SIM800



OK



ERR
h
AT+CMGF=1


OK


i
AT+CMGS="8327978415"




j
Hello User


k

end



+CMGS: 25
5



OK








pi@raspberrypi:~/Desktop $ sudo python GSMcall.py
start
a
AT


b
ATE0

ï¿½
c
ATE0


OK

d
AT+CVHU=0


OK

e
ATI


SIM800 R13.08
f
AT+GMM


SIMCOM_SIM800

g
AT+CPMS="SM","SM",SM"



OK


h
AT+CMGF=1


OK


i
ATD8327978415


j
Hello User


k

end










pi@raspberrypi:~/Desktop $ sudo python GSMcall.py
start
a
AT


b
ATE0


c
ATE0


OK


d
AT+CVHU=0

Traceback (most recent call last):
  File "GSMcall.py", line 49, in <module>
    rcv = port.read(10)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 490, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
AT


b
ATE0


c
ATE0


OK

d
AT+CVHU=0


OK

e
ATI


SIM800 R13.08
f
AT+GMM

SMM_SM00

g
AT+CPMS="SM","SM",SM"


h
AT+CMGF=1




i
AT+CMGS="8327978415"


j
Hello User


k

end










pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
AT


b
ATE0


c
ATE0


d
AT+CVHU=0


e
ATI


f
AT+GMM


g
AT+CPMS="SM","SM",SM"

h
AT+CMGF=1


i
AT+CMGS="8327978415"


j
Hello User


k

end


 0






Traceback (most recent call last):
  File "GSM.py", line 122, in <module>
    rcv = port.read(10)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 490, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
AT


OK

b
ATE0


OK

c
ATE0


OK

d
AT+CVHU=0


OK

e
ATI


SIM800 R13.08
f
AT+GMM


SIMCOM_SIM800

g
AT+CPMS="SM","SM",SM"



OK


h
AT+CMGF=1


OK


i
AT+CMGS="8327978415"




j
Hello User


k

end










pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
AT


b
ATE0


c
ATE0



OK


d
AT+CVHU=0


OK


e
ATI


SIM800 R13.08

f
AT+GMM




OK



SIMCOM
g
AT+CPMS="SM","SM",SM"
_SIM800



OK


h
AT+CMGF=1



ERROR


i
AT+CMGS="8327978415"


ERROR


j
Hello User


k

end










pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
AT


b
ATE0


c
ATE0


OK

d
AT+CVHU=0


OK

e
ATI


SIM800 R13.08
f
AT+GMM

SMM_SM00

g
AT+CPMS="SM","SM",SM"


h
AT+CMGF=1

O


i
AT+CMGS="8327978415"


j
Hello User


k

end










pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
AT


b
ATE0


c
ATE0


d
AT+CVHU=0


e
ATI


f
AT+GMM


g
AT+CPMS="SM","SM",SM"

h
AT+CMGF=1


i
AT+CMGS="8327978415"


j
Hello User


k

end




+CMGS: 2







pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
flush
Traceback (most recent call last):
  File "GSM.py", line 18, in <module>
    sleep(1)
NameError: name 'sleep' is not defined
pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
flush
AT


OK

b
ATE0


OK

c
ATE0


OK

d
AT+CVHU=0


OK

e
ATI


SIM800 R13.08
f
AT+GMM


SIMCOM_SIM800

g
AT+CPMS="SM","SM",SM"



OK


h
AT+CMGF=1


OK


i
AT+CMGS="8327978415"




j
Hello User


k

end



+CMGS: 3




OK








pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
flush
AT


b
ATE0


c
ATE0



OK


d
AT+CVHU=0


OK


e
ATI


SIM800 R13.08

f
AT+GMM




OK


g
AT+CPMS="SM","SM",SM"


SIMCOM_SIM800



O
h
AT+CMGF=1


OK


i
AT+CMGS="8327978415"

Traceback (most recent call last):
  File "GSM.py", line 107, in <module>
    rcv = port.read(10)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 490, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
flush
AT


b
ATE0


c
ATE0


d
AT+CVHU=0


e
ATI


f
AT+GMM


g
AT+CPMS="SM","SM",SM"

h
AT+CMGF=1


i
AT+CMGS="8327978415"


j
Hello User


k

end




+CMGS:


OK







pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
flush
AT


b
ATE0



OK


c
ATE0


OK


d
AT+CVHU=0


OK


e
ATI



SIM800 R13.08
f
AT+GMM


SIMCOM_SIM800

g
AT+CPMS="SM","SM",SM"

h
AT+CMGF=1


ERROR


i
AT+CMGS="8327978415"




j
Hello User


k

end






OK









pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
flush
AT


b
ATE0


c
ATE0


OK

d
AT+CVHU=0


OK

e
ATI


SIM800 R13.08
f
AT+GMM

SMM_SM00

g
AT+CPMS="SM","SM",SM"


h
AT+CMGF=1




i
AT+CMGS="8327978415"


j
Hello User


k

end










pi@raspberrypi:~/Desktop $ sudo python GSM.py
start
a
flush
AT


b
ATE0


c
ATE0


d
AT+CVHU=0


e
ATI


f
AT+GMM


g
AT+CPMS="SM","SM",SM"

h
AT+CMGF=1


i
AT+CMGS="8327978415"


j
Hello User


k

end


 6




Traceback (most recent call last):
  File "GSM.py", line 128, in <module>
    rcv = port.read(10)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 490, in read
    'device reports readiness to read but returned no data '
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
pi@raspberrypi:~/Desktop $ ^C
pi@raspberrypi:~/Desktop $ 

